"""Where a control came from, and what that is worth.

Every control in Prama is generated by something, and the user is entitled to
ask "why does this exist?" and get an answer better than "somebody added it in
March". Provenance is that answer, and it is attached at generation rather than
written afterwards, so it cannot be absent and cannot be wrong.

**Origins are ranked, because they are not equally trustworthy.** A person
declaring that a row is one position per account per day is stating a fact about
their business; a miner observing that the combination happens to be unique
today is stating a fact about one snapshot of data. Both are worth having. Only
the first is worth enforcing without asking.

The ranking earns its keep at the moment two origins produce the same control.
The naive handling is to deduplicate and keep either one, which throws away the
most interesting thing that can happen here: **mining agreeing with a
declaration is independent evidence that the declaration is true.** So the
higher authority wins the control and the other becomes corroboration, recorded
on it. A steward reviewing "you declared this and the data independently
confirms it" approves in a second; the same control with the mining silently
discarded takes a minute and a query.

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
"""

from __future__ import annotations

import dataclasses
import enum
import hashlib
from typing import Any

from prama.core import pjson


class Origin(enum.Enum):
    """How a control came to be proposed."""

    #: A person stated a fact about their business. The strongest origin, and
    #: the only one that is authoritative about *intent* rather than about data.
    DECLARATION = "declaration"
    #: Brought in from dbt, Soda or Great Expectations. Somebody wrote it
    #: deliberately, elsewhere, and it carries their intent even though Prama
    #: cannot see the reasoning.
    IMPORT = "import"
    #: Extracted from a data dictionary or a regulatory instruction, with the
    #: passage it came from retained. Strong, because the citation is checkable.
    DOCUMENT = "document"
    #: Observed to hold in the data. Says nothing about whether it *should*.
    MINING = "mining"
    #: Generalised from a handful of labelled cells.
    EXAMPLE = "example"
    #: Proposed by a model. The weakest, and never applied without review.
    INDUCTION = "induction"

    @property
    def authority(self) -> int:
        """Higher wins when two origins produce the same control."""
        return _AUTHORITY[self]

    @property
    def is_stated(self) -> bool:
        """Whether a person meant it, as opposed to it being true today."""
        return self in (Origin.DECLARATION, Origin.IMPORT, Origin.DOCUMENT)

    @property
    def may_auto_activate(self) -> bool:
        """Whether a control from this origin may run without a review step.

        Only a declaration. Everything else is a proposal — including mining,
        which is right about the data and silent about the intent: a column that
        happens to be unique in today's extract is not a declared key, and
        enforcing it turns the first legitimate duplicate into an incident.
        """
        return self is Origin.DECLARATION

    @property
    def label(self) -> str:
        return _LABELS[self]


_AUTHORITY: dict[Origin, int] = {
    Origin.DECLARATION: 100,
    Origin.DOCUMENT: 80,
    Origin.IMPORT: 60,
    Origin.MINING: 40,
    Origin.EXAMPLE: 30,
    Origin.INDUCTION: 20,
}

_LABELS: dict[Origin, str] = {
    Origin.DECLARATION: "you declared it",
    Origin.DOCUMENT: "a document says so",
    Origin.IMPORT: "it was imported from an existing suite",
    Origin.MINING: "it holds in the data",
    Origin.EXAMPLE: "it generalises examples you labelled",
    Origin.INDUCTION: "a model proposed it",
}


@dataclasses.dataclass(frozen=True, slots=True)
class Citation:
    """A passage a rule was taken from, so the rule can be disputed.

    Required for `Origin.DOCUMENT` (`FR-IND-012`). A rule extracted from a
    regulatory instruction without the sentence it came from is unfalsifiable:
    nobody can check it, so nobody will trust it, so it will not be approved.
    """

    document: str
    #: The passage, quoted rather than paraphrased. A paraphrase is the model's
    #: reading, and the reading is exactly what is in dispute.
    quote: str
    locator: str = ""
    #: A hash of the document as read, so a later edit is detectable. A rule
    #: whose source has changed underneath it is not necessarily wrong, but it
    #: is no longer supported by what the citation points at.
    document_hash: str = ""

    def render(self) -> str:
        where = f", {self.locator}" if self.locator else ""
        return f"{self.document}{where}: “{self.quote}”"

    def to_dict(self) -> dict[str, Any]:
        return {
            "document": self.document,
            "quote": self.quote,
            "locator": self.locator,
            "document_hash": self.document_hash,
        }


@dataclasses.dataclass(frozen=True, slots=True)
class Corroboration:
    """A second origin that independently produced the same control."""

    origin: Origin
    detail: str

    def render(self) -> str:
        return f"{self.origin.label} — {self.detail}"

    def to_dict(self) -> dict[str, Any]:
        return {"origin": self.origin.value, "detail": self.detail}


@dataclasses.dataclass(frozen=True, slots=True)
class Provenance:
    """Why a control exists, in a form that can be shown to its owner."""

    origin: Origin
    #: The generator rule, miner or prompt template. Named so a systematically
    #: bad rule can be found and fixed once rather than per control.
    rule: str
    #: What it was derived from: a declaration id, a document URI, a mined
    #: profile run. The link the UI follows when somebody asks "why?".
    source_ref: str = ""
    #: The declarer's own words, kept verbatim. This is what goes in BECAUSE,
    #: and paraphrasing it would replace the business's language with ours.
    statement: str = ""
    declared_by: str = ""
    #: ISO-8601 UTC. "Because you declared it on 4 March" needs the date.
    declared_at: str = ""
    citation: Citation | None = None
    #: For mined rules: what was observed, so the observation can be re-run.
    observations: tuple[str, ...] = ()
    corroborations: tuple[Corroboration, ...] = ()

    def __post_init__(self) -> None:
        if self.origin is Origin.DOCUMENT and self.citation is None:
            raise ValueError(
                "a rule attributed to a document must carry the passage it came "
                "from; without one it cannot be checked, and an unfalsifiable "
                "rule will not be approved"
            )

    @property
    def authority(self) -> int:
        return self.origin.authority

    @property
    def is_corroborated(self) -> bool:
        return bool(self.corroborations)

    def corroborated_by(self, other: Provenance, detail: str) -> Provenance:
        """Record that *other* independently produced the same control.

        The interesting case rather than a housekeeping one: a declaration the
        data independently confirms is approved in a second, and the same
        control with its corroboration discarded takes a minute and a query.
        """
        addition = Corroboration(origin=other.origin, detail=detail)
        if any(c.origin is addition.origin for c in self.corroborations):
            return self
        return dataclasses.replace(self, corroborations=(*self.corroborations, addition))

    def sentence(self) -> str:
        """The answer to "why does this control exist?", for a person.

        Assembled from the parts rather than stored, because a stored sentence
        drifts from the provenance it describes — and this one is read at three
        in the morning by somebody deciding whether an alert matters.
        """
        parts: list[str] = []
        if self.origin is Origin.DECLARATION and self.declared_by:
            when = f" on {_day(self.declared_at)}" if self.declared_at else ""
            parts.append(f"{self.declared_by} declared it{when}")
        else:
            parts.append(self.origin.label.capitalize())
        if self.statement:
            parts.append(f"“{self.statement}”")
        if self.citation is not None:
            parts.append(self.citation.render())
        if self.observations:
            parts.append("; ".join(self.observations))
        if self.corroborations:
            parts.append(
                "independently confirmed by "
                + " and ".join(c.render() for c in self.corroborations)
            )
        return ". ".join(parts).replace("..", ".")

    def to_dict(self) -> dict[str, Any]:
        return {
            "origin": self.origin.value,
            "rule": self.rule,
            "source_ref": self.source_ref,
            "statement": self.statement,
            "declared_by": self.declared_by,
            "declared_at": self.declared_at,
            "citation": self.citation.to_dict() if self.citation else None,
            "observations": list(self.observations),
            "corroborations": [c.to_dict() for c in self.corroborations],
            "sentence": self.sentence(),
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> Provenance:
        citation = data.get("citation")
        return cls(
            origin=Origin(data["origin"]),
            rule=data.get("rule", ""),
            source_ref=data.get("source_ref", ""),
            statement=data.get("statement", ""),
            declared_by=data.get("declared_by", ""),
            declared_at=data.get("declared_at", ""),
            citation=Citation(**citation) if citation else None,
            observations=tuple(data.get("observations", ())),
            corroborations=tuple(
                Corroboration(origin=Origin(c["origin"]), detail=c["detail"])
                for c in data.get("corroborations", ())
            ),
        )


def _day(timestamp: str) -> str:
    """The date part of an ISO-8601 stamp, for a sentence a person reads."""
    return timestamp.split("T", 1)[0] if timestamp else ""


def identity(*parts: str) -> str:
    """A stable identifier for a generated control.

    Derived from what the control *is about* — the declaration, the rule, the
    subject — and deliberately not from its text. Editing a threshold must
    update the existing control rather than orphan one and create another;
    otherwise re-running the generator after any edit produces an estate of
    duplicates that nobody recognises, and the review queue fills with controls
    that already exist.

    The text is what the *content* hash covers, and the difference between the
    two is exactly what a review diff shows.
    """
    digest = hashlib.sha256(pjson.canonical(list(parts))).hexdigest()
    return digest[:32]


def content_hash(text: str) -> str:
    """A hash of the rendered control, for detecting that it changed."""
    return hashlib.sha256(text.encode("utf-8")).hexdigest()[:32]
