"""The Medium article: its images exist, and its diagrams pass their rendered audit.

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
"""

from __future__ import annotations

import re
import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
ARTICLE = ROOT / "docs" / "publications" / "medium" / "your-dashboard-is-green.md"
IMAGES = ROOT / "docs" / "publications" / "medium" / "img"


def test_every_image_the_article_uses_exists_and_every_diagram_is_used() -> None:
    used = set(re.findall(r"\]\((img/[^)]+\.png)\)", ARTICLE.read_text(encoding="utf-8")))
    assert len(used) >= 8, "anti-vacuity: the article's images were not found at all"
    assert not [u for u in used if not (ARTICLE.parent / u).is_file()]
    for png in IMAGES.glob("*.png"):
        assert f"img/{png.name}" in used, f"{png.name} is drawn but never shown"
        assert png.with_suffix(".svg").is_file(), f"{png.name} has no source"


def test_the_article_credits_its_author_and_no_tool() -> None:
    text = ARTICLE.read_text(encoding="utf-8").lower()
    assert "ashutosh sinha" in text
    assert not [w for w in ("co-authored", "generated by", "generated with", "claude") if w in text]


@pytest.mark.slow
@pytest.mark.skipif(shutil.which("inkscape") is None, reason="the audit needs Inkscape")
def test_the_diagrams_have_nothing_printed_over_anything() -> None:
    result = subprocess.run(
        [sys.executable, str(ROOT / "tools" / "medium" / "diagrams.py"), "--check"],
        capture_output=True,
        text=True,
        timeout=600,
    )
    assert "no diagram issues detected" in result.stdout, result.stdout + result.stderr
