"""The deck, checked by the tools that claim to check it.

``tools/deck/GUIDE.md`` makes two audits the shipping gate for the deck: the geometry
audit, from estimates, and the rendered audit, from what LibreOffice actually lays out.
A gate wired into no test is a gate somebody forgets, so both run here, the slide count
is asserted (a part module that silently lost slides still builds), and the file is
checked to name its author and no tool.

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[2]
TOOLS = ROOT / "tools" / "deck"
DECK = ROOT / "docs" / "deck" / "Prama-Evidence-First-Data-Quality.pptx"
SLIDES = 45
# Anywhere in the file: no tool or assistant credited as a maker of the deck.
FORBIDDEN = ("python-pptx", "generated by", "generated with", "co-authored")
# In the document properties, which describe the file itself, stricter still. Provider
# names are allowed on a slide (the gateway slide lists the providers Prama supports);
# in the properties they could only be a credit.
FORBIDDEN_IN_PROPERTIES = (*FORBIDDEN, "generated", "claude", "anthropic")


def _run(script: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, str(TOOLS / script), str(DECK)],
        capture_output=True,
        text=True,
        cwd=ROOT,
        timeout=600,
    )


def test_the_deck_has_no_geometry_issues() -> None:
    pytest.importorskip("pptx")
    result = _run("audit.py")
    assert "no geometry issues detected" in result.stdout, result.stdout + result.stderr


@pytest.mark.slow
@pytest.mark.skipif(
    not (shutil.which("soffice") or shutil.which("libreoffice")) or not shutil.which("pdftotext"),
    reason="the rendered audit needs LibreOffice and poppler's pdftotext",
)
def test_the_rendered_deck_has_nothing_printed_over_anything() -> None:
    result = _run("render_audit.py")
    assert "no rendered issues detected" in result.stdout, result.stdout + result.stderr


def test_the_deck_has_the_slides_the_guide_claims() -> None:
    pptx = pytest.importorskip("pptx")
    assert len(pptx.Presentation(str(DECK)).slides) == SLIDES
    assert f"| {SLIDES} |" in (TOOLS / "GUIDE.md").read_text(encoding="utf-8")


def test_the_deck_names_its_author_and_no_tool() -> None:
    pptx = pytest.importorskip("pptx")
    prs = pptx.Presentation(str(DECK))
    props = prs.core_properties
    assert props.author == "Ashutosh Sinha" and props.last_modified_by == "Ashutosh Sinha"
    fields = " ".join(
        f or "" for f in (props.title, props.subject, props.comments, props.keywords)
    ).lower()
    assert not [w for w in FORBIDDEN_IN_PROPERTIES if w in fields]
    text = []
    for slide in prs.slides:
        for shape in slide.shapes:
            if shape.has_text_frame:
                text.append(shape.text_frame.text)
            if getattr(shape, "has_table", False):
                text.extend(c.text for r in shape.table.rows for c in r.cells)
    lowered = " ".join(text).lower()
    assert not [w for w in FORBIDDEN if w in lowered]


def test_the_audits_can_see_what_they_claim_to() -> None:
    """A guard on the gate. An audit that skipped tables would pass a deck full of
    collisions, and a rendered audit that never compared words would pass anything."""
    geometry = (TOOLS / "audit.py").read_text(encoding="utf-8")
    assert "has_table" in geometry and "is_opaque" in geometry
    rendered = (TOOLS / "render_audit.py").read_text(encoding="utf-8")
    assert "printed over each other" in rendered and "reaches the footer rule" in rendered
