#!/usr/bin/env python3
"""Generate the reference documents that must not be written by hand.

Two of them: the CLI reference and the configuration reference. Both describe
things the code already knows, and a hand-written copy of either is a second
source of truth that drifts in the flattering direction — a flag that was
renamed, a setting that was removed, an option nobody documented.

    python3 scripts/generate_docs.py --write    # regenerate
    python3 scripts/generate_docs.py --check    # refuse if they have drifted

`--check` is what the gate runs. A generated document edited by hand fails it,
which is the point: the fix is to change the code and regenerate, not to correct
the prose and leave the code saying something else.

What is deliberately *not* generated: every word of judgement. The runbook, the
troubleshooting guide and the design corpus are written by a person, because
they say why rather than what, and nothing in the code knows why.

Copyright (c) 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.
"""

from __future__ import annotations

import argparse
import io
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

BANNER = (
    "<!-- Generated by scripts/generate_docs.py. Do not edit by hand:\n"
    "     run `python3 scripts/generate_docs.py --write` instead. The gate\n"
    "     refuses a version that has drifted from the code. -->\n"
)

_LOCKUP = (
    '<img src="../assets/prama-lockup.svg" '
    'alt="Prama — Declare it. Prove it. Trust it." width="330"/>'
)

HEADER = f"""{_LOCKUP}

*Copyright © 2026 Ashutosh Sinha <ajsinha@gmail.com>. All rights reserved.*

---

"""


def cli_reference() -> str:
    """Every command, from the parser that actually runs."""
    from prama.cli.base import Application
    from prama.cli.commands import all_commands

    application = Application(all_commands())
    out = io.StringIO()
    out.write(BANNER)
    out.write(HEADER)
    out.write("# CLI reference\n\n")
    out.write(
        "Every command Prama ships, taken from the argument parser itself. If a\n"
        "flag is here it exists; if it is not here it does not.\n\n"
        "Exit codes are uniform across the tool: **0** success, **1** the command\n"
        "could not be completed, **2** the command line was wrong, **3** the thing\n"
        "being checked is wrong and must not be used. The last one is the\n"
        "distinction that matters in CI — a contract breach and a broken pipeline\n"
        "need different people.\n\n"
    )

    commands = sorted(application._commands.items())
    out.write("| Command | What it does |\n|---|---|\n")
    for name, command in commands:
        out.write(f"| [`prama {name}`](#prama-{name}) | {command.help} |\n")
    out.write("\n---\n\n")

    for name, command in commands:
        out.write(f"## `prama {name}`\n\n{command.help}\n\n")
        children = getattr(command, "_commands", None)
        if children:
            out.write("| Subcommand | What it does |\n|---|---|\n")
            for sub_name, sub in sorted(children.items()):
                out.write(f"| `prama {name} {sub_name}` | {sub.help} |\n")
            out.write("\n")
            for sub_name, sub in sorted(children.items()):
                arguments = _arguments(sub)
                if arguments:
                    out.write(f"**`prama {name} {sub_name}`**\n\n")
                    out.write(arguments)
        else:
            arguments = _arguments(command)
            if arguments:
                out.write(arguments)
        out.write("\n")
    return out.getvalue()


def _arguments(command: Any) -> str:
    import argparse as ap

    parser = ap.ArgumentParser(add_help=False)
    try:
        command.configure(parser)
    except Exception:  # pragma: no cover - a command that needs more than a parser
        return ""
    rows = []
    for action in parser._actions:
        if action.dest == "help":
            continue
        flags = ", ".join(f"`{o}`" for o in action.option_strings) or f"`{action.dest}`"
        required = " **required**" if action.required else ""
        choices = f" One of: {', '.join(str(c) for c in action.choices)}." if action.choices else ""
        helptext = (action.help or "").replace("|", "\\|")
        rows.append(f"| {flags}{required} | {helptext}{choices} |")
    if not rows:
        return ""
    return "| Argument | Meaning |\n|---|---|\n" + "\n".join(rows) + "\n"


def configuration_reference() -> str:
    """Every setting, from the shipped configuration file."""
    import yaml

    document = yaml.safe_load((ROOT / "config" / "application.yaml").read_text())
    raw = (ROOT / "config" / "application.yaml").read_text().splitlines()

    #: The trailing comment on a line is the only description a setting has, and
    #: it is the one a reader of the file already sees. Lifting it here keeps one
    #: explanation rather than two.
    comments: dict[str, str] = {}
    path: list[str] = []
    for line in raw:
        if not line.strip() or line.strip().startswith("#"):
            continue
        indent = len(line) - len(line.lstrip())
        depth = indent // 2
        key = line.strip().split(":", 1)[0]
        path = [*path[:depth], key]
        if "#" in line:
            comments[".".join(path)] = line.split("#", 1)[1].strip()

    out = io.StringIO()
    out.write(BANNER)
    out.write(HEADER)
    out.write("# Configuration reference\n\n")
    out.write(
        "Every setting in `config/application.yaml`, with its shipped default.\n\n"
        "**Secrets do not belong in this file.** It is tracked in Git, and the\n"
        "pre-commit hook refuses a non-empty secret in it. Put real credentials in\n"
        "`config/application.local.yaml`, which is git-ignored, or reference them\n"
        "(`env://PRAMA_DB_PASSWORD`).\n\n"
        "**`security.session_secret` ships empty on purpose.** A fresh clone\n"
        "refuses to boot rather than starting with a key everybody knows.\n\n"
        "Any setting can be overridden by an environment variable: upper-case the\n"
        "path and join it with double underscores, so `database.sqlite.path`\n"
        "becomes `PRAMA_DATABASE__SQLITE__PATH`.\n\n"
    )
    out.write("| Setting | Default | Meaning |\n|---|---|---|\n")
    for key, value in _flatten(document):
        default = "*(empty)*" if value in ("", None) else f"`{value}`"
        # A shipped comment often lists alternatives as `a | b | c`, and an
        # unescaped pipe silently ends the table cell — producing a reference
        # whose columns are wrong wherever the explanation is most useful.
        meaning = str(comments.get(key, "")).replace("|", "\\|")
        out.write(f"| `{key}` | {default} | {meaning} |\n")
    return out.getvalue()


def _flatten(node: Any, prefix: str = "") -> list[tuple[str, Any]]:
    rows: list[tuple[str, Any]] = []
    if isinstance(node, dict):
        for key, value in node.items():
            rows.extend(_flatten(value, f"{prefix}.{key}" if prefix else str(key)))
    elif isinstance(node, list):
        rows.append((prefix, ", ".join(str(v) for v in node) if node else ""))
    else:
        rows.append((prefix, node))
    return rows


def metrics_reference() -> str:
    """Every metric at GET /metrics, from the registry the code exports."""
    import prama.telemetry.openlineage_http  # noqa: F401  (registers its counter)
    from prama.telemetry import metrics

    out = io.StringIO()
    out.write(BANNER)
    out.write(HEADER)
    out.write("# Metrics reference\n\n")
    out.write(
        "Prama's own operational metrics, exported at `GET /metrics` in the Prometheus\n"
        "text format. Labels name kinds (a verdict, an assertion kind, a route\n"
        "template, a purpose), never a control, a dataset or a tenant, so the number\n"
        "of series does not grow with the estate. Each metric caps its series at\n"
        f"{metrics.MAX_SERIES}; past it, new label values fold into `other`, counted by\n"
        "`prama_metric_series_folded_total`.\n\n"
        "These measure Prama. None of them is ever an input to a data quality score.\n\n"
        "See [observability.md](observability.md) for the endpoints, tracing and\n"
        "OpenLineage, and the Helm values.\n\n"
    )
    out.write("| Metric | Type | Labels | Meaning |\n|---|---|---|---|\n")
    for name, metric in sorted(metrics.REGISTRY._metrics.items()):
        labels = ", ".join(f"`{label}`" for label in metric.labels) or "—"
        out.write(f"| `{name}` | {metric.kind} | {labels} | {metric.help} |\n")
    out.write(
        "| `prama_metric_series_folded_total` | counter | — | Observations folded into "
        "`other` because a metric reached its series cap. |\n"
    )
    return out.getvalue()


TARGETS = {
    "docs/operations/cli-reference.md": cli_reference,
    "docs/operations/configuration-reference.md": configuration_reference,
    "docs/operations/metrics-reference.md": metrics_reference,
}


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    drifted = []
    for relative, build in TARGETS.items():
        path = ROOT / relative
        fresh = build()
        if args.write:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(fresh, encoding="utf-8")
            print(f"wrote {relative}")
        else:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != fresh:
                drifted.append(relative)

    if drifted:
        print(
            "these generated documents no longer match the code:\n  "
            + "\n  ".join(drifted)
            + "\n\nRun: python3 scripts/generate_docs.py --write",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print(f"every generated document matches the code ({len(TARGETS)} checked)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
